/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaces;

import com.clases.FacturaClase;
import com.clases.MetodosDB;
import com.clases.Productos;
import javax.swing.ImageIcon;

/**
 *
 * @author Jhoan
 */
public class Vender extends javax.swing.JFrame {

    MetodosDB metdb = new MetodosDB();
    int y, x;

    /**
     * Creates new form Factura
     */
    public Vender() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Errordatosincorrectos.setVisible(false);
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/Iconos/Iconobarra2.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVender = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Errordatosincorrectos = new javax.swing.JLabel();
        Vender = new javax.swing.JLabel();
        Cancelar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Regresarbtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelVender.setBackground(new java.awt.Color(255, 255, 255));
        PanelVender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        PanelVender.setPreferredSize(new java.awt.Dimension(250, 350));
        PanelVender.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelVenderMouseDragged(evt);
            }
        });
        PanelVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelVenderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelVenderMousePressed(evt);
            }
        });
        PanelVender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/venderproducto.png"))); // NOI18N
        Titulo.setText("Agregar Producto");
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TituloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TituloMouseExited(evt);
            }
        });
        PanelVender.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 50));

        txtNombre.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelVender.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 170, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setText("Ingrese el nombre");
        PanelVender.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        Errordatosincorrectos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Errordatosincorrectos.setForeground(new java.awt.Color(255, 51, 51));
        Errordatosincorrectos.setText("Datos incorrectos ");
        PanelVender.add(Errordatosincorrectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        Vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/comercio.png"))); // NOI18N
        Vender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VenderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VenderMouseExited(evt);
            }
        });
        PanelVender.add(Vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 50, 50));

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/disgusto.png"))); // NOI18N
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarMouseExited(evt);
            }
        });
        PanelVender.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 50, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Cancelar");
        PanelVender.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Vender");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        PanelVender.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelVender.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel2.setText("Ingrese la cantidad");
        PanelVender.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Minimize.png"))); // NOI18N
        Minimizar.setText("jLabel2");
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        PanelVender.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 20, 20));

        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png"))); // NOI18N
        Regresarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseExited(evt);
            }
        });
        PanelVender.add(Regresarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelVender, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelVender, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderMouseClicked

        if (this.metdb.existeono(this.txtNombre.getText()) == true) {
            Productos prod = this.metdb.Buscarproducto(this.txtNombre.getText());
            //resta la cantidad actual de productos con la cantidad exigida y si pasa continua la funcion
            int Cantidadavender, cantidadactual;
            Cantidadavender = Integer.parseInt(this.txtCantidad.getText());
            cantidadactual = Integer.parseInt(prod.getCantidad());

            //en una variable short busca el producto le saca las ventas y le suma la cantidad del jfield
            short Ventasdesde = (short) (Short.parseShort(prod.getVentasDesde())
                    + Short.parseShort(this.txtCantidad.getText()));

            try {
                if (cantidadactual >= Cantidadavender) {
                    cantidadactual = cantidadactual - Cantidadavender;
                    this.metdb.EditarProducto("prod_cantidad", cantidadactual + "", this.txtNombre.getText());

                    this.metdb.EditarProducto("ventas_desde", Ventasdesde + "",
                            this.txtNombre.getText());

                    this.Errordatosincorrectos.setVisible(false);
                    
                    Factura fact = new Factura(new FacturaClase(prod.getPrecioDeVenta(), this.txtCantidad.getText(), prod.getNombre()));
                    fact.setVisible(true);
                    this.PonerEnBlancoTxt();
                    this.dispose();
                    
                } else {
                    this.Errordatosincorrectos.setVisible(true);
                    this.Errordatosincorrectos.setText("Error no hay disponibles tantos productos");
                }

            } catch (Exception e) {
                System.out.println("Errroe en vender " + e);
            }

        } else {
            this.Errordatosincorrectos.setVisible(true);
        }


    }//GEN-LAST:event_VenderMouseClicked

    private void VenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderMouseEntered
        Vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/comercio-de-personas.png"))); // NOI18N

    }//GEN-LAST:event_VenderMouseEntered

    private void VenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderMouseExited
        Vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/comercio.png"))); // NOI18N

    }//GEN-LAST:event_VenderMouseExited

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        this.regresar();
    }//GEN-LAST:event_CancelarMouseClicked

    private void CancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseEntered
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/disgusto (1).png"))); // NOI18N

    }//GEN-LAST:event_CancelarMouseEntered

    private void CancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseExited
        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/disgusto.png"))); // NOI18N

    }//GEN-LAST:event_CancelarMouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void PanelVenderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVenderMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_PanelVenderMouseDragged

    private void PanelVenderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVenderMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_PanelVenderMousePressed

    private void TituloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseEntered
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/venderproductoazul.png"))); // NOI18N

    }//GEN-LAST:event_TituloMouseEntered

    private void TituloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseExited
        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/venderproducto.png"))); // NOI18N

    }//GEN-LAST:event_TituloMouseExited

    private void PanelVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVenderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelVenderMouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void RegresarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseClicked
        this.regresar();
    }//GEN-LAST:event_RegresarbtnMouseClicked

    private void RegresarbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseEntered
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras azul.png")));
    }//GEN-LAST:event_RegresarbtnMouseEntered

    private void RegresarbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseExited
        Regresarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atrasnegro.png")));
    }//GEN-LAST:event_RegresarbtnMouseExited
    public void regresar() {
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }

    public void PonerEnBlancoTxt() {

        this.txtNombre.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cancelar;
    private javax.swing.JLabel Errordatosincorrectos;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JPanel PanelVender;
    private javax.swing.JLabel Regresarbtn;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Vender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
